version: '3.8'
services:
  maven-app:
    build: .
    volumes:
      - .:/app
    command: mvn clean compile exec:java -Dexec.mainClass="com.artistryhub.console.Consult"

  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: artistryhub
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
